baseURL = "https://hubai.se"
languageCode = "en-us"
title = 'Hub AI'
defaultContentLanguage = "en"
"pagination.pagerSize" = 7
theme = "spectral"
enableEmoji=true

[markup.goldmark.renderer]
unsafe= true

[params]
fancyTitle = '&nbsp<img width="250px" src="/complete_white_logo.png"/>&nbsp'
copyright = "Hub AI"
description = "Bringing people from all disciplines together to talk about Artificial Intelligence"
startbuttonText = "Our Events"
startbuttonLink = "/events"
body_is_markdown = true

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/events/'
title = "Events"

[[params.menu.main]]
url = '/recruitment/'
title = "Join Us"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.about]
enable = true
title = 'About Us'
body = '''
Hub AI is a student organization that organizes events related to the applications of AI for students at Lund University. Our events range from guest lectures and panel discussions to Python workshops and social events. Since Hub AI hosts interdisciplinary events, we attract students with different backgrounds ranging from engineering, biotechnology and computer science to economics, political science and psychology
'''

[params.two]
enable = true

[[params.two.section]]
img = "educate.jpg"
title = 'Guest Lectures'
body = 'One of our most common types of events are guest lectures or colloquiums. Such events revolve around one or several professionals who are invited to talk about a particular area related to AI. Some previous examples include Brain-Inspired Computing, AI in Diagnosing Mental Illness, Smart Cities, Thesis Writing or Entrepreneurship in Tech'

[[params.two.section]]
img = "share.jpg"
title = 'Panel Discussions'
body = 'Some topics make it more beneficial to have a discussion between several people to capture a wider perspective. Hence, we also host panel events. Our panel discussions welcome professionals, scholars or students to discuss topics such as Diversity in AI, AI and Sustainability or Life Science meets AI'

[[params.two.section]]
img = "workshop.jpg"
title = 'Python Workshops'
body = 'Each semester we host a series of Python workshops. There are six workshops in total with the first three being designed for beginners, while the remaining ones cover more complex concepts building on top of material covered in the previous workshops'

[[params.two.section]]
img = "social.png"
title = 'Social Events'
body = 'As an organization, we aim to create a community for like-minded people, which is why we also host less formal social events with greater flexibility in terms of exact format. Such events range from board game nights and pizza mingles to going hiking or bowling'

[params.three]
enable = true
title = 'The Board'
body = '''
The board members are the main drivers shaping what type of events we host and are responsible for the day-to-day activities of the organization
'''

# NOTE! File size really matters for the website's responsiveness. Decrease the size and compress images.
[[params.three.feature]]
headshot = '<img src="team/oltina2.jpg"/ class="headshot">'
title = "President"
name = "Oltina Lungu"
body = "I am a Master’s student in European Business Law with professional experience at the intersection of AI and other fields. Passionate about innovation, I wish to integrate it into our lives in a fair and ethical way. I stay informed by attending weekly AI engineering classes and remaining open to new opportunities for growth. At Hub AI, I lead the organization toward our goals, overseeing administration, coordinating within the team and with external partners, and serving as spokesperson at events and meetings. I believe that approaching our work with curiosity, kindness, and respect for others will unlock best opportunities in AI projects."

[[params.three.feature]]
headshot = '<img src="team/mariia.jpg"/ class="headshot">'
name = "Mariia Lesina"
title = "Vice President"
body = "I am a Master’s student in Human Rights Studies at Lund University and an Innovation intern at UNDP. Having a professional background of two years as an AI Ethics Specialist, I view making AI more ethical and transparent as my main career goal."
[[params.three.feature]]
headshot = '<img src="team/diana.jpg"/ class="headshot">'
name = "Diana Nadyrova"
title = "Head of External Partnerships"
body = "I am a Bachelor’s student in Economy and Society with a strong interest in how artificial intelligence interacts with economics, policy, and society. \n As Head of External Partnerships at HubAI, I work on building meaningful connections between students, organizations, and industry partners. I focus on creating collaborations that go beyond single events and instead grow into long-term relationships that support learning, innovation, and real-world impact. Through partnerships, I aim to help HubAI act as a bridge between students and real-world applications of AI."

[[params.three.feature]]
headshot = '<img src="team/alexander.jpg"/ class="headshot">'
name = "Alexander Tzikas"
title = "Head of Education"
body = "I am a bachelor student in Business Administration and Economics with a personal interest in AI, machine learning, and technology in general. My particular interest is in how AI can be applied in finance and data analysis, and how these applications can drive growth and innovation. As Head of Education, I help spread knowledge about topics related to the more technical side of AI. Together with my team, I organize workshops in programming and the practical applications of various AI tools."

[[params.three.feature]]
headshot = '<img src="team/luzie.webp"/ class="headshot">'
name = "Luzie Nickel"
title = "Head of Events"
body = "I am a third year Bachelor’s student in Biomedicine and really interested in how to connect AI use and Science and especially use it to further understand complicated systems. Other than that, my interest also lies in ethical questions and dilemmas concerning the use of AI. As the head of events, I am working together with other committees to bring everything together and make the events something you look forward to."

[[params.three.feature]]
headshot = '<img src="team/katya2.jpg"/ class="headshot">'
name = "Ekaterina Gulina"
title = "Head of Development"
body = "I’m currently studying for a Master’s in Cultural Criminology, with a strong interest in how artificial intelligence is reshaping familiar social structures. I find it fascinating to explore how AI transforms the way we understand crime and culture and how it might influence these dynamics in the future. My goal is to critically examine these changes and contribute to discussions about the ethical and societal impacts of AI in a rapidly evolving world."

[[params.three.feature]]
headshot = '<img src="team/hannes.jpg"/ class="headshot">'
name = "Hannes Cederholm"
title = "Treasurer"
body = "As a Bachelor’s student in Business Administration, I am drawn to understanding the impact of AI on the labor market and its role in enhancing business performance. The rapid rise of AI brings significant uncertainty about its potential and impact on society, and I want to explore it on a deeper level to prepare for the transformations it may bring."

[[params.three.feature]]
headshot = '<img src="team/steve.jpeg"/ class="headshot">'
name = "Steve Sunny Emmanuel"
title = "Head of Marketing"
body = "I’m pursuing a Master’s in Strategic Communication at Lund University, exploring how communication shapes human relationships in an age of technology. I’m fascinated by how AI challenges and redefines what it means to be human — our creativity, empathy, and connection. At Hub AI Lund, I help bridge people from different fields so that AI becomes more understandable, responsible, and deeply human-centered."

[params.one]
enable = true
title = 'Our Goals'
body = '''
<ol class="ol-center">
    <li class="li-space">Establishing a forum to discuss Artificial Intelligence for students at Lund University</li>
    <li class="li-space">Educating students on current research within AI, through theory and practice by hosting events such as guest lectures, panel debates, and Python workshops</li>
    <li class="li-space">Forging links between students and creating a comfortable environment to meet like-minded people, to network, and socialize</li>
    <li class="li-space">Connecting students with potential professional opportunities within the industry such as research, internships, and graduate positions by hosting events where students can meet representatives from different institutions</li>
</ol>
'''

[[params.one.icon]]
icon = "fa-book"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-handshake-o"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "fa-users"
style = "3"
label = "Dolor"

[params.cta]
enable = true
title = "What we're up to..."
body = "Read about our upcoming and past events here"

[[params.cta.link]]
href = "/events/"
text = "Events"
special = true

[[params.cta.link]]
href = "/recruitment/"
text = "Join Us"
special = false

#[params.contact]
#enable = true
#title = "Contact"
#body = "Leave us a message."
#phone = "+49 (0) 030 000 000"
#address = "Sandgatan 2, 223 50<br />Lund, Skåne 0000<br />Sweden"
#subject = "New message from website"
#plain = false

[params.social]
facebook = "HubAILund"
instagram = "hubailund"
linkedin = "company/hubai/"
email = "hello@hubai.se"
privacy_policy = "https://docs.google.com/document/d/125UiXliA1pm2etY3MclWvEGSWVDwHtvFtYR3FqCuym0/edit?usp=drive_link"
footerImage = '''
    <img height="128" width="128" src="/af.png"/>
    <img height="128" width="128" src="/AILund.png"/>
'''
